version: '3.8'

services:
  app:
    image: muhalwan/devops-webapp:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped