          pipeline {
              agent any

              environment {
                  DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
                  AWS_CREDENTIALS = credentials('aws-credentials')
                  KUBECONFIG_CREDENTIALS = credentials('kubeconfig')
              }

              stages {
                  stage('Checkout') {
                      steps {
                          git 'https://github.com/muhalwan/devops-webapp.git'
                      }
                  }

                  stage('Build') {
                      steps {
                          sh 'npm install'
                          sh 'npm test'
                      }
                  }

                  stage('Docker Build') {
                      steps {
                          script {
                              dockerImage = docker.build("muhalwan/devops-webapp:${env.BUILD_ID}")
                          }
                      }
                  }

                  stage('Docker Push') {
                      steps {
                          script {
                              docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
                                  dockerImage.push()
                              }
                          }
                      }
                  }

                  stage('Deploy to Kubernetes') {
                      steps {
                          withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                              sh 'kubectl apply -f k8s/'
                          }
                      }
                  }
              }

              post {
                  success {
                      echo 'Deployment successful!'
                  }
                  failure {
                      echo 'Deployment failed.'
                  }
              }
          }